spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo_jpa_schema
    username: demo_jpa
    password: my-secret-pw11
  jpa:
    hibernate:
      ddl-auto: create
    sho-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect